# Generated by Django 5.1.8 on 2025-04-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_alter_issue_lecturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='lecturer',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
