# Generated by Django 5.1.8 on 2025-04-03 15:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_alter_issue_lecturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='requires_profile_setup',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='academicregistrar',
            name='managed_students',
            field=models.ManyToManyField(blank=True, related_name='registrars', to='issues.student'),
        ),
        migrations.AlterField(
            model_name='academicregistrar',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registrar_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lecturer_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student',
            name='year_of_study',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
