# Generated by Django 5.1.7 on 2025-03-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='category',
            field=models.CharField(choices=[('missing marks', 'Missing marks'), ('appeals', 'Appeals'), ('corrections', 'Corrections')], default='missing marks', max_length=20),
        ),
    ]
