# Generated by Django 5.1.7 on 2025-03-29 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_issue_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issues.department'),
        ),
    ]
