# Generated by Django 5.1.8 on 2025-04-03 11:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='reporter',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='title',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='issue',
            name='category',
            field=models.CharField(choices=[('academic', 'Academic'), ('administrative', 'Administrative'), ('technical', 'Technical'), ('other', 'Other')], default='academic', max_length=20),
        ),
        migrations.AddField(
            model_name='issue',
            name='coursecode',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issue',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='issue_documents/'),
        ),
        migrations.AddField(
            model_name='issue',
            name='lecturer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_issues', to='issues.lecturer'),
            preserve_default=False,
        ),
    ]
