# Generated by Django 5.1.8 on 2025-04-03 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_remove_issue_assigned_to_remove_issue_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='lecturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_issues', to='issues.lecturer'),
        ),
    ]
