# Generated by Django 5.2 on 2025-04-17 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0008_issue_title_issue_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='user',
            new_name='owner',
        ),
    ]
