# Generated by Django 5.2 on 2025-04-19 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0011_issue_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('pending', 'Pending'), ('assigned', 'Assigned'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=10),
        ),
    ]
