# Generated by Django 5.2 on 2025-04-24 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0012_issue_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='lecturer',
        ),
    ]
