# Generated by Django 5.2 on 2025-04-24 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0013_remove_issue_lecturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='lecturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='issues.lecturerprofile'),
        ),
    ]
